### ISSUE TITLE
Choose a CSS framework: Bootstrap chosen due to some extensions

### ISSUE THREAD

**Issue by asponring** [determinedWaffle/ThumbsCheck#29]

**Comment by Berkana** [comment]
Bootstrap has been eliminated. They don't have sliders; if Fred wants an analog/continuous thumb scale, we will need sliders.

Foundation has sliders. I'm checking out jQuery Mobile UI now.

**Comment by Berkana** [comment]
https://angular-ui.github.io/bootstrap/#/rating

This looks interesting, but it might not work as well with a touch interface.

_UPDATE_

https://github.com/angular-ui/bootstrap would work fine if the user simply clicks on what level of the rating .
