### ISSUE TITLE
when switching between quiz questions in instructor view a type error fires in console.log

### ISSUE THREAD

**Issue by DaveDH2** [determinedWaffle/ThumbsCheck#90]
I found this error when trying to refactor $scope.total:

Bug does not break anything, only a console.error, progress bar and total count functionality works fine. 

TypeError: Cannot read property '$value' of null
    at instructorQuiz.js:117

line: 117var response = responses[key][key];

**Comment by mikeyao** [comment]
After your awesome refactor? Are we still experience this error? I can try to fix it tmr.
